services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173" 
    networks:
      - ai-net
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: main-backend
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app
    networks:
      - ai-net
    restart: unless-stopped

  stable-diffusion-webui:
    build:
      context: ./stable-diffusion-webui
    container_name: stable-diffusion-webui
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./stable-diffusion-webui:/app
    networks:
      - ai-net
    restart: unless-stopped

networks:
  ai-net:
    driver: bridge
